// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PageService.Infrastructure;

#nullable disable

namespace PageService.Infrastructure.Migrations
{
    [DbContext(typeof(PageDbContext))]
    partial class PageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PageService.Domain.Entity.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "IsDeleted");

                    b.ToTable("T_Pages", (string)null);
                });

            modelBuilder.Entity("PageService.Domain.Entity.Page", b =>
                {
                    b.OwnsOne("PageService.Domain.ValueObject.AdditionalField", "OptionField", b1 =>
                        {
                            b1.Property<Guid>("PageId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("PrivateField")
                                .IsRequired()
                                .IsUnicode(true)
                                .HasColumnType("longtext");

                            b1.Property<string>("PublicField")
                                .IsRequired()
                                .IsUnicode(true)
                                .HasColumnType("longtext");

                            b1.HasKey("PageId");

                            b1.ToTable("T_Pages");

                            b1.WithOwner()
                                .HasForeignKey("PageId");
                        });

                    b.Navigation("OptionField")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
